<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "template"
 *
 * Auto generated by Extension Builder 2016-08-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Template',
	'description' => 'Template Distribution',
	'category' => 'distribution',
	'author' => 'Markus Sattler',
	'author_email' => 'mail@markus-sattler.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'version' => '',
			'filemetadata' => '',
			'mask' => '',
			'news' => '',
			'powermail' => '',
			'realurl' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);